### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by dzurikmiroslav** [monarco/node-red-contrib-monarco-hat#3]
Hello,
On fresh installed Raspberry Pi OS with NodeRED (installed by https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered) 
In NodeRED pallete when I try install node-red-contrib-monarco-hat package I got error:

```
13 May 12:47:19 - [info] Installing module: node-red-contrib-monarco-hat, version: 1.0.4
13 May 12:48:05 - [warn] Installation of module node-red-contrib-monarco-hat failed:
13 May 12:48:05 - [warn] ------------------------------------------
13 May 12:48:05 - [warn] npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm ERR! code 1
npm ERR! path /home/pi/.node-red/node_modules/spi-device
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! make: Entering directory '/home/pi/.node-red/node_modules/spi-device/build'
npm ERR!   CXX(target) Release/obj.target/spi/src/spi.o
npm ERR!   CXX(target) Release/obj.target/spi/src/spidevice.o
npm ERR!   CXX(target) Release/obj.target/spi/src/open.o
npm ERR!   CXX(target) Release/obj.target/spi/src/close.o
npm ERR!   CXX(target) Release/obj.target/spi/src/transfer.o
npm ERR!   CXX(target) Release/obj.target/spi/src/getoptions.o
npm ERR! make: Leaving directory '/home/pi/.node-red/node_modules/spi-device/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.15.0 | linux | arm
npm ERR! gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v16.15.0/node-v16.15.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.15.0/node-v16.15.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v16.15.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.15.0/SHASUMS256.txt
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/pi/.node-red/node_modules/spi-device/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/pi/.cache/node-gyp/16.15.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/pi/.cache/node-gyp/16.15.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/pi/.cache/node-gyp/16.15.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/pi/.node-red/node_modules/spi-device',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../../nan/nan.h:292,
npm ERR!                  from ../src/getoptions.cc:4:
npm ERR! ../../nan/nan_new.h: In instantiation of ‘typename Nan::imp::Factory<T>::return_t Nan::New(A0) [with T = v8::Uint32; A0 = long unsigned int; typename Nan::imp::Factory<T>::return_t = v8::Local<v8::Uint32>]’:
npm ERR! ../src/getoptions.cc:35:65:   required from here
npm ERR! ../../nan/nan_new.h:208:30: error: call of overloaded ‘New(long unsigned int&)’ is ambiguous
npm ERR!   208 |   return imp::Factory<T>::New(arg0);
npm ERR!       |          ~~~~~~~~~~~~~~~~~~~~^~~~~~
npm ERR! In file included from ../../nan/nan_new.h:189,
npm ERR!                  from ../../nan/nan.h:292,
npm ERR!                  from ../src/getoptions.cc:4:
npm ERR! ../../nan/nan_implementation_12_inl.h:177:1: note: candidate: ‘static Nan::imp::FactoryBase<v8::Uint32>::return_t Nan::imp::Factory<v8::Uint32>::New(int32_t)’
npm ERR!   177 | Factory<v8::Uint32>::New(int32_t value) {
npm ERR!       | ^~~~~~~~~~~~~~~~~~~
npm ERR! ../../nan/nan_implementation_12_inl.h:183:1: note: candidate: ‘static Nan::imp::FactoryBase<v8::Uint32>::return_t Nan::imp::Factory<v8::Uint32>::New(uint32_t)’
npm ERR!   183 | Factory<v8::Uint32>::New(uint32_t value) {
npm ERR!       | ^~~~~~~~~~~~~~~~~~~
npm ERR! make: *** [spi.target.mk:121: Release/obj.target/spi/src/getoptions.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 5.15.32-v7+
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/pi/.node-red/node_modules/spi-device
npm ERR! gyp ERR! node -v v16.15.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-05-13T10_47_20_812Z-debug-0.log
13 May 12:48:05 - [warn] ------------------------------------------
Error: Install failed
    at /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/installer.js:285:25
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
13 May 12:48:05 - [error] Error: Install failed
```

I was try use different version of nodejs (12, 14), but not solve the problem...

Thanks in advance!

**Comment by clickworkorange** [comment]
I am seeing this issue as well - as helpfully pointed out by [Steve-Mcl](https://discourse.nodered.org/u/steve-mcl) on the Node-RED forum this may be because `node-red-contrib-monarco-hat` depends on `spi-device` version 2, which had [a possibly related bug](https://github.com/fivdi/spi-device/issues/21#issuecomment-866885923).. It's a little beyond me, but could have something to do with 32 vs 64-bit `long` size on ARMv7/8? In any case, this bug has long since been fixed in `spi-device`, and it may be that upgrading and testing the dependency is all that's needed is to fix the problem. I'll see what I can do.

**Comment by clickworkorange** [comment]
I can confirm that changing the dependency in [`monarco-hat-driver-nodejs`](https://github.com/monarco/monarco-hat-driver-nodejs/blob/master/package.json) from `"spi-device": "^2.0.0"` to `"spi-device": "^3.1.2"` fixes the issue, and lets `node-red-contrib-monarco-hat` install without errors. I have not been able to test this in action, since the only Monarco-Hat I own is in use, but looking at [the history of `spi-device`](https://github.com/fivdi/spi-device/blob/master/History.md) I'd say there's a good chance it will. It seems the fix appeared in 3.1.2.

**Comment by J450N-B3RRY** [comment]
I too had this install problem, I have downloaded the git repository and edited the line `"spi-device": "^3.1.2"` in `(https://github.com/monarco/monarco-hat-driver-nodejs/blob/master/package.json)` followed by npm install. and it still fails with spi issue. how to get the "node-red-contrib-monatco-hat" to look locally for the driver?

**Comment by jreitinger** [comment]
Hi everyone, thanks for reporting the issue. We modified _[monarco-hat-driver-nodejs](https://github.com/monarco/monarco-hat-driver-nodejs)_ and everything should work now. Special thanks to @clickworkorange for tracking down the issue. P.S.: My colleague apologizes for deleting the pull-request.
